name: Backend Tests

on:
  push:
    branches: [ "**" ]  # Run on all branches
  pull_request:
    branches: [ "**" ]  # Run on all branches

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install pipenv and dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install

      - name: Run all tests
        run: |
          cd backend
          pipenv run python manage.py test
