name: Full Stack Tests

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install pipenv and dependencies
        run: |
          cd testalready/backend
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install

      - name: Run backend tests
        run: |
          cd testalready/backend
          pipenv run python manage.py test

  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd testalready/frontend
          npm install

      - name: Run frontend tests
        run: |
          cd testalready/frontend
          npm run test:quick
